language: node_js
sudo: false
dist: trusty
node_js:
  - 14.16.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
  chrome: stable
branches:
  except:
    - g3
cache: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export CXX="g++-5"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - "./aio/deploy-cn.sh"
