language: node_js
sudo: false
dist: trusty
node_js:
  - 10.13.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  chrome: stable
branches:
  except:
    - g3
cache: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - "./aio/deploy-cn.sh"
